### ISSUE TITLE
第一个容器化应用和 Yaml 文件

### ISSUE THREAD

**Issue by barry-boy** [barry-boy/barry-boy.github.io#33]
```
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  namespace: linux39
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata: 
      labels: 
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```
