### ISSUE TITLE
告警示例

### ISSUE THREAD

**Issue by barry-boy** [barry-boy/barry-boy.github.io#35]
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus
    meta.helm.sh/release-namespace: kube-prometheus
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.8.1
    chart: kube-prometheus-stack-45.8.1
    heritage: Helm
    release: kube-prometheus
  name: demo-rules
  namespace: kube-prometheus
spec:
  groups:
    - name: "your-application-name.rules"
      rules:
        - alert: PodDown
          for: 1m
          expr: sum(up{job="your-service-monitor-name"}) < 1 or absent(up{job="your-service-monitor-name"})
          annotations:
            message: The deployment has less than 1 pod running.
```
